version: "3"
services:
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - mongo-db:/data/db:ro
  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env
    environment:
      - MONGO_URL=mongodb://nosql-db:27017/products
    command: npm run dev
    
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    # depends_on:
    #   - "nosql-db"
    volumes:
      - .:/app
      - /app/shopping/node_modules
    env_file:
      - ./shopping/.env
    command: npm run dev
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    # depends_on:
    #   - "nosql-db"

    volumes:
      - .:/app/
      - /app/customer/node_modules
    env_file:
      - ./customer/.env
    command: npm run dev

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80


volumes:
  mongo-db: